In [21]:
import pandas as pd
import sys
import os
sys.path.append(os.path.abspath(os.path.join('..')))
from funcoes.funcoes_exploratoria import *

In [ ]:
df_original = pd.read_csv('../dados/data_raw.csv')
df_original

In [26]:
analise_dados(df_original)

,Tipos de Dados,Qtd_Não_Nulos,Valores Únicos,Qtd_Nulos,% Nulos,Duplicados
id,int64,21613,21436,0,0.0%,0
date,object,21613,372,0,0.0%,0
price,float64,21613,4028,0,0.0%,0
bedrooms,int64,21613,13,0,0.0%,0
bathrooms,float64,21613,30,0,0.0%,0
sqft_living,int64,21613,1038,0,0.0%,0
sqft_lot,int64,21613,9782,0,0.0%,0
floors,float64,21613,6,0,0.0%,0
waterfront,int64,21613,2,0,0.0%,0
view,int64,21613,5,0,0.0%,0
condition,int64,21613,5,0,0.0%,0
grade,int64,21613,12,0,0.0%,0
sqft_above,float64,21611,946,2,0.01%,0
sqft_basement,int64,21613,306,0,0.0%,0
yr_built,int64,21613,116,0,0.0%,0
yr_renovated,int64,21613,70,0,0.0%,0
zipcode,int64,21613,70,0,0.0%,0
lat,float64,21613,5034,0,0.0%,0
long,float64,21613,752,0,0.0%,0
sqft_living15,int64,21613,777,0,0.0%,0
sqft_lot15,int64,21613,8689,0,0.0%,0

In [27]:
# Correção do datetime
df_tratado = df_original.copy()
df_tratado['date'] = pd.to_datetime(df_tratado['date'])
df_tratado['date'].astype

<bound method NDFrame.astype of 0       2014-10-13
1       2014-12-09
2       2015-02-25
3       2014-12-09
4       2015-02-18
           ...
21608   2014-05-21
21609   2015-02-23
21610   2014-06-23
21611   2015-01-16
21612   2014-10-15
Name: date, Length: 21613, dtype: datetime64[ns]>

In [25]:
analise_dados(df_tratado)

,Tipos de Dados,Qtd_Não_Nulos,Valores Únicos,Qtd_Nulos,% Nulos,Duplicados
id,int64,21613,21436,0,0.0%,0
date,datetime64[ns],21613,372,0,0.0%,0
price,float64,21613,4028,0,0.0%,0
bedrooms,int64,21613,13,0,0.0%,0
bathrooms,float64,21613,30,0,0.0%,0
sqft_living,int64,21613,1038,0,0.0%,0
sqft_lot,int64,21613,9782,0,0.0%,0
floors,float64,21613,6,0,0.0%,0
waterfront,int64,21613,2,0,0.0%,0
view,int64,21613,5,0,0.0%,0
condition,int64,21613,5,0,0.0%,0
grade,int64,21613,12,0,0.0%,0
sqft_above,float64,21611,946,2,0.01%,0
sqft_basement,int64,21613,306,0,0.0%,0
yr_built,int64,21613,116,0,0.0%,0
yr_renovated,int64,21613,70,0,0.0%,0
zipcode,int64,21613,70,0,0.0%,0
lat,float64,21613,5034,0,0.0%,0
long,float64,21613,752,0,0.0%,0
sqft_living15,int64,21613,777,0,0.0%,0
sqft_lot15,int64,21613,8689,0,0.0%,0

In [34]:
# Confirmando os id repetidos
df_id = df_tratado[df_tratado.duplicated(subset=['id'], keep=False)] 
df_id.sort_values(by='id')

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
2496,1000102,2014-09-16,280000.0,6,3.00,2400,9373,2.0,0,0,...,7,2400.0,0,1991,0,98002,47.3262,-122.214,2060,7316
2497,1000102,2015-04-22,300000.0,6,3.00,2400,9373,2.0,0,0,...,7,2400.0,0,1991,0,98002,47.3262,-122.214,2060,7316
16814,7200179,2014-10-16,150000.0,2,1.00,840,12750,1.0,0,0,...,6,840.0,0,1925,0,98055,47.4840,-122.211,1480,6969
16815,7200179,2015-04-24,175000.0,2,1.00,840,12750,1.0,0,0,...,6,840.0,0,1925,0,98055,47.4840,-122.211,1480,6969
11433,109200390,2014-08-20,245000.0,3,1.75,1480,3900,1.0,0,0,...,7,1480.0,0,1980,0,98023,47.2977,-122.367,1830,6956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6345,9828200460,2014-06-27,260000.0,2,1.00,700,4800,1.0,0,0,...,7,700.0,0,1922,0,98122,47.6147,-122.300,1440,4800
15200,9834200305,2015-02-10,615000.0,3,1.00,1790,3876,1.5,0,0,...,7,1090.0,700,1904,0,98144,47.5750,-122.288,1360,4080
15199,9834200305,2014-07-16,350000.0,3,1.00,1790,3876,1.5,0,0,...,7,1090.0,700,1904,0,98144,47.5750,-122.288,1360,4080
1086,9834200885,2015-04-20,550000.0,4,2.50,2080,4080,1.0,0,0,...,7,1040.0,1040,1962,0,98144,47.5720,-122.290,1340,4080
1085,9834200885,2014-07-17,360000.0,4,2.50,2080,4080,1.0,0,0,...,7,1040.0,1040,1962,0,98144,47.5720,-122.290,1340,4080

In [ ]:
# Procurando dados duplicados
df_tratado.duplicated().sum()

np.int64(0)

In [4]:
resumo_estatistico(df_original)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,21613.0,21613,21613.0,21613.0,21613.0,21613.0,21613.0,21613.0,21613.0,21613.0,...,21613.0,21611.0,21613.0,21613.0,21613.0,21613.0,21613.0,21613.0,21613.0,21613.0
unique,-,372,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
top,-,20140623T000000,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
freq,-,142,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
mean,4580301520.86,-,540088.14,3.37,2.11,2079.9,15106.97,1.49,0.01,0.23,...,7.66,1788.4,291.51,1971.01,84.4,98077.94,47.56,-122.21,1986.55,12768.46
std,2876565571.31,-,367127.2,0.93,0.77,918.44,41420.51,0.54,0.09,0.77,...,1.18,828.13,442.58,29.37,401.68,53.51,0.14,0.14,685.39,27304.18
min,1000102.0,-,75000.0,0.0,0.0,290.0,520.0,1.0,0.0,0.0,...,1.0,290.0,0.0,1900.0,0.0,98001.0,47.16,-122.52,399.0,651.0
25%,2123049194.0,-,321950.0,3.0,1.75,1427.0,5040.0,1.0,0.0,0.0,...,7.0,1190.0,0.0,1951.0,0.0,98033.0,47.47,-122.33,1490.0,5100.0
50%,3904930410.0,-,450000.0,3.0,2.25,1910.0,7618.0,1.5,0.0,0.0,...,7.0,1560.0,0.0,1975.0,0.0,98065.0,47.57,-122.23,1840.0,7620.0
75%,7308900445.0,-,645000.0,4.0,2.5,2550.0,10688.0,2.0,0.0,0.0,...,8.0,2210.0,560.0,1997.0,0.0,98118.0,47.68,-122.12,2360.0,10083.0
max,9900000190.0,-,7700000.0,33.0,8.0,13540.0,1651359.0,3.5,1.0,4.0,...,13.0,9410.0,4820.0,2015.0,2015.0,98199.0,47.78,-121.32,6210.0,871200.0

In [ ]:
contagem_valores(df_original)

In [7]:
df = df_original.copy()
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180.0,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170.0,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770.0,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050.0,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680.0,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530.0,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310.0,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020.0,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600.0,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020.0,0,2008,0,98144,47.5941,-122.299,1020,1357